# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_LOCATION: back-end/Streamlined-Dev-Job-Searcher-API/Streamlined-Dev-Job-Searcher-API.csproj


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT_LOCATION
    - name: Build
      run: dotnet build --no-restore $PROJECT_LOCATION
    - name: Test
      run: dotnet test --no-build --verbosity normal $PROJECT_LOCATION
